"""Policy I/O + conservative, safe-by-default policy generation.

Static, advisory only: Frontier Scout *emits* a policy; it does not *enforce* it
at runtime. ``load_policy`` mirrors :mod:`frontier_scout.policy`'s resilience —
it never raises; on a missing/unreadable/malformed file it returns a conservative
default plus a human-readable warning.
"""

from __future__ import annotations

import json
import os
from pathlib import Path

from pydantic import ValidationError

from .models import AgentPolicy, ScanResult

__all__ = [
    "default_policy_path",
    "generate_policy",
    "conservative_default_policy",
    "load_policy",
    "save_policy",
    "explain_policy",
    "DEFAULT_BLOCKED_SHELL",
    "DEFAULT_ALLOWED_SHELL",
    "DEFAULT_PROTECTED",
]

POLICY_FILENAME = "frontier-scout.policy.json"

# Hard cap on a policy file we will read into memory (a JSON policy is tiny;
# this is a memory-amplification guard on the operator-supplied --policy path).
MAX_POLICY_BYTES = 1_000_000

# Conservative defaults (design §8) -----------------------------------------

DEFAULT_BLOCKED_SHELL: list[str] = [
    "rm -rf",
    "sudo",
    "chmod 777",
    "git push --force",
    "git push -f",
    "curl | sh",
    "curl | bash",
    "wget | sh",
    "eval",
    ":(){",
    "mkfs",
    "dd if=",
    "> /dev/sda",
]

DEFAULT_ALLOWED_SHELL: list[str] = [
    "ls",
    "cat",
    "git status",
    "git diff",
    "git log",
    "grep",
    "find",
    "pytest",
    "ruff",
    "mypy",
    "black",
]

# Protected-by-default globs: secrets, CI, infra/deploy, schema migrations.
DEFAULT_PROTECTED: list[str] = [
    "**/.env",
    "**/.env.*",
    "**/*.pem",
    "**/*.key",
    "**/id_rsa",
    "**/credentials*",
    "**/.npmrc",
    "**/.pypirc",
    "**/secrets/**",
    ".github/workflows/**",
    "**/migrations/**",
    "**/alembic/**",
    "infra/**",
    "deploy/**",
    "**/*.tf",
    "**/k8s/**",
    "**/helm/**",
    "**/Dockerfile",
    "**/docker-compose*.y*ml",
]

DEFAULT_ALLOWED_FILE_GLOBS: list[str] = ["src/**", "tests/**", "**/*.py", "**/*.md"]

DEFAULT_APPROVAL_GATES: list[str] = [
    "network",
    "shell",
    "credential",
    "write",
    "protected-path",
    "ci",
    "deploy",
]

POLICY_NOTES = (
    "Conservative starter generated by `frontier-scout agent policy init`. "
    "Advisory only — Frontier Scout emits this policy; it does not enforce it "
    "at runtime. Review and tighten before relying on it."
)

# Surface kinds whose paths should be folded into the protected globs.
_PROTECTED_SURFACE_KINDS = frozenset({"secret-likely", "ci", "deploy-config", "protected-path"})

# Extension-less filenames that are concrete files, not directories — so the
# glob heuristic treats them as ``<path>`` rather than ``<path>/**``.
_KNOWN_FILES = frozenset(
    {
        "Dockerfile",
        "Makefile",
        "Jenkinsfile",
        "Procfile",
        "id_rsa",
        "id_dsa",
        ".npmrc",
        ".pypirc",
        ".netrc",
        ".cursorrules",
    }
)


def default_policy_path(repo: str) -> str:
    """Return ``<repo>/frontier-scout.policy.json``."""

    return os.path.join(repo, POLICY_FILENAME)


def _path_to_glob(path: str, kind: str) -> str:
    """Convert a scanned surface path to a glob.

    A ``.env`` family path → ``**/.env*``; a directory-like path → ``<path>/**``;
    anything else (a concrete file) → ``<path>`` unchanged.
    """

    name = path.rsplit("/", 1)[-1]
    if name == ".env" or name.startswith(".env."):
        return "**/.env*"
    if name in _KNOWN_FILES:
        # A concrete, extension-less file (Dockerfile, Makefile, …) → match it
        # directly, not as a directory.
        return path
    # Heuristic: a path whose final component has no extension is treated as a
    # directory (the scanner emits bare dir names like ``migrations`` and
    # ``.github/workflows``); anything with a real extension is a file.
    if "." not in name.lstrip("."):
        return f"{path}/**"
    return path


def generate_policy(scan: ScanResult) -> AgentPolicy:
    """Build a conservative, safe-by-default :class:`AgentPolicy` from a scan."""

    protected = list(DEFAULT_PROTECTED)
    for surface in scan.surfaces:
        if surface.kind in _PROTECTED_SURFACE_KINDS:
            glob = _path_to_glob(surface.path, surface.kind)
            if glob not in protected:
                protected.append(glob)

    allowed_shell = list(DEFAULT_ALLOWED_SHELL)
    for check in scan.detected_checks:
        if check not in allowed_shell:
            allowed_shell.append(check)

    return AgentPolicy(
        version=1,
        allowed_tools=[],
        blocked_tools=[],
        allowed_shell_commands=allowed_shell,
        blocked_shell_commands=list(DEFAULT_BLOCKED_SHELL),
        allowed_file_globs=list(DEFAULT_ALLOWED_FILE_GLOBS),
        protected_file_globs=protected,
        mcp_server_allowlist=[],
        required_checks=list(scan.detected_checks),
        approval_gates=list(DEFAULT_APPROVAL_GATES),
        policy_notes=POLICY_NOTES,
    )


def conservative_default_policy() -> AgentPolicy:
    """A deny-by-default policy used whenever a policy file can't be loaded.

    This is the **fail-closed** fallback: it blocks dangerous shell, protects
    secrets/CI/deploy/migrations, gates every risky surface, and keeps the MCP
    allowlist empty. Never return a bare ``AgentPolicy()`` for a load failure —
    an empty policy is fail-*open* (it allows everything).
    """

    return AgentPolicy(
        allowed_shell_commands=list(DEFAULT_ALLOWED_SHELL),
        blocked_shell_commands=list(DEFAULT_BLOCKED_SHELL),
        allowed_file_globs=list(DEFAULT_ALLOWED_FILE_GLOBS),
        protected_file_globs=list(DEFAULT_PROTECTED),
        approval_gates=list(DEFAULT_APPROVAL_GATES),
        policy_notes=(
            "Conservative fail-closed default (no valid policy file was loaded). "
            "Run `frontier-scout agent policy init` to generate one."
        ),
    )


def save_policy(policy: AgentPolicy, path: str) -> None:
    """Write ``policy`` to ``path`` as pretty JSON with a trailing newline."""

    Path(path).write_text(json.dumps(policy.model_dump(), indent=2) + "\n")


def load_policy(path: str) -> tuple[AgentPolicy, list[str]]:
    """Load a policy, never crashing — and failing **closed**.

    Returns ``(policy, warnings)``. A missing, oversized, unreadable, or
    malformed file yields :func:`conservative_default_policy` (deny-by-default,
    **not** an empty/permissive policy) plus a human-readable warning. A valid
    file yields the validated policy and an empty warning list.
    """

    p = Path(path)
    if not p.exists():
        return conservative_default_policy(), [
            f"policy file not found: {path}; using conservative default"
        ]
    try:
        if p.stat().st_size > MAX_POLICY_BYTES:
            return conservative_default_policy(), [
                f"policy {path} too large (> {MAX_POLICY_BYTES} bytes); "
                "using conservative default"
            ]
        data = json.loads(p.read_text())
        return AgentPolicy.model_validate(data), []
    except (OSError, ValueError, ValidationError):
        # JSONDecodeError and pydantic ValidationError both subclass ValueError;
        # OSError covers read failures. Fail CLOSED to the conservative default.
        return conservative_default_policy(), [
            f"could not parse policy {path}; using conservative default"
        ]


def explain_policy(policy: AgentPolicy) -> str:
    """Render a policy as human-readable advisory text."""

    def _section(title: str, items: list[str]) -> list[str]:
        if not items:
            return [f"{title}: (none)"]
        return [f"{title}:"] + [f"  - {item}" for item in items]

    lines: list[str] = [
        "Frontier Scout agent policy (advisory)",
        "Frontier Scout emits this policy; it does not enforce it at runtime.",
        f"Policy version: {policy.version}",
        "",
    ]
    lines += _section("Allowed tools", policy.allowed_tools)
    lines += _section("Blocked tools", policy.blocked_tools)
    lines += _section("Allowed shell commands", policy.allowed_shell_commands)
    lines += _section("Blocked shell commands", policy.blocked_shell_commands)
    lines += _section("Allowed file globs", policy.allowed_file_globs)
    lines += _section("Protected file globs", policy.protected_file_globs)
    lines += _section("MCP server allowlist", policy.mcp_server_allowlist)
    lines += _section("Required checks", policy.required_checks)
    lines += _section("Approval gates", policy.approval_gates)
    if policy.policy_notes:
        lines += ["", "Notes:", f"  {policy.policy_notes}"]
    return "\n".join(lines)
